controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# Define the route for the Swagger UI
app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui
        # Specify the area if you have multiple areas configured
        area: default
